(function(){
  const specific={
    'Pozitif Tam Sayıların Çarpanları':['Bir sayıyı kalansız bölen pozitif tam sayılar o sayının çarpanlarıdır.','Çarpan çiftlerini sistemli yaz.','1 ve sayının kendisini unutma.','36 için 1·36, 2·18, 3·12, 4·9, 6·6.','Çarpan ile kat kavramını karıştırma.'],
    'Asal Çarpanlara Ayırma':['Bir doğal sayıyı asal sayıların çarpımı biçiminde yazmaya asal çarpanlara ayırma denir.','2,3,5,7 gibi asal sayılarla böl.','Üslü gösterimi doğru kullan.','72=2³·3².','1 asal sayı değildir.'],
    'EBOB ve EKOK':['EBOB ortak bölenlerin en büyüğü, EKOK ortak katların en küçüğüdür.','Paylaştırma/gruplama sorularında EBOB; tekrar-buluşma sorularında EKOK düşün.','Asal çarpan yöntemi hız kazandırır.','24=2³·3, 36=2²·3² → EBOB=12, EKOK=72.','Sorunun EBOB mu EKOK mu istediğini anlamadan işleme başlama.'],
    'Bilimsel Gösterim':['Çok büyük veya çok küçük sayılar a×10ⁿ biçiminde yazılır ve 1≤|a|<10 olmalıdır.','Virgülün kaç basamak taşındığını say.','Küçük sayılarda üs genellikle negatiftir.','0,00045=4,5×10⁻⁴.','Katsayıyı 10 veya daha büyük bırakma.'],
    'Kareköklü İfadelerde İşlemler':['Toplama ve çıkarmada benzer köklü ifadeler birleştirilir; çarpma ve bölmede kök içleri birlikte işleme alınabilir.','Önce kökleri sadeleştir.','√a·√b=√ab ilişkisini kullan.','3√5+2√5=5√5.','Kök içleri farklı ifadeleri doğrudan toplama.'],
    'Pisagor Bağıntısı':['Dik üçgende dik kenarların kareleri toplamı hipotenüsün karesine eşittir.','Hipotenüs dik açının karşısındadır.','a²+b²=c² düzenini doğru kur.','3-4-5 üçgeninde 3²+4²=5².','Hipotenüsü yanlış kenar seçme.'],
    'Konu ve Ana Fikir':['Konu metnin ne anlattığını, ana fikir yazarın vermek istediği temel mesajı söyler.','Konuyu birkaç kelimeyle, ana fikri yargı cümlesiyle ifade et.','Başlık ve tekrar eden kavramlara bak.','Kitap okumanın yararlarını anlatan metinde konu “kitap okuma”, ana fikir “kitap okumak gelişimi destekler” olabilir.','Konu ile ana fikri aynı şey sanma.'],
    'Fiilimsiler':['Fiilden türeyip cümlede isim, sıfat veya zarf görevi yapan sözcüklerdir.','İsim-fiil, sıfat-fiil, zarf-fiil eklerini tanı.','Fiilimsi yüklem olmaz.','“Koşarak geldi.” cümlesinde “koşarak” zarf-fiildir.','Her ek gördüğünde otomatik fiilimsi sanma; sözcüğün görevine bak.'],
    'Yazım Kuralları':['Büyük harfler, birleşik kelimeler, sayıların yazımı ve bağlaç/ek ayrımı temel yazım alanlarıdır.','de/da bağlacı ayrı, bulunma eki bitişik yazılır.','ki bağlacı ile -ki ekini ayır.','“Ben de geliyorum.” doğru yazımdır.','Sözcüğü cümleden çıkarınca anlam büyük ölçüde korunuyorsa de/da bağlaç olabilir.'],
    'Mevsimlerin Oluşumu':['Mevsimler Dünya’nın eksen eğikliği ve Güneş çevresindeki dolanımı sonucu oluşur.','Eksen eğikliği yaklaşık 23,5°’dir.','Yarım küreler aynı anda zıt mevsimleri yaşar.','21 Haziran civarında Kuzey Yarım Küre daha dik ışın alır.','Mevsimleri Dünya-Güneş uzaklığıyla açıklama.'],
    'Kalıtım':['Kalıtım, özelliklerin genler aracılığıyla nesilden nesile aktarılmasıdır.','Gen DNA’nın işlevsel bir bölümüdür.','Genotip gen yapısı, fenotip gözlenebilir özelliktir.','Aa bireyde A baskınsa baskın fenotip görülür.','Baskın özelliği “daha güçlü/iyi” olarak yorumlama.'],
    'Katı Basıncı':['Katı basıncı uygulanan kuvvetle doğru, temas alanıyla ters orantılıdır.','P=F/A mantığını kullan.','Aynı ağırlıkta alan küçülürse basınç artar.','İnce topuk zemine daha büyük basınç uygular.','Kuvvet ile basıncı aynı kavram sanma.'],
    'Atatürk İlkeleri':['Cumhuriyetçilik, milliyetçilik, halkçılık, devletçilik, laiklik ve inkılapçılık temel ilkelerdir.','İnkılabı hangi amacı gerçekleştirdiğine göre ilkeyle eşleştir.','Millî egemenlik → Cumhuriyetçilik bağlantısını bil.','Saltanatın kaldırılması Cumhuriyetçilikle doğrudan ilişkilidir.','Bir inkılabın birden fazla ilkeyle ilişkili olabileceğini unutma.'],
    'Lozan Barış Antlaşması':['24 Temmuz 1923’te imzalanan Lozan, yeni Türk devletinin bağımsızlığının uluslararası alanda tanınmasında temel antlaşmadır.','Kapitülasyonların kaldırılmasını bağımsızlıkla ilişkilendir.','Sevr ile Lozan’ın sonuçlarını karşılaştır.','Kapitülasyonların kaldırılması ekonomik ve hukuki egemenliği güçlendirdi.','Lozan’ı Mudanya Ateşkesi ile karıştırma.'],
    'Kader ve Kaza İnancı':['Kader Allah’ın her şeyi ölçü ve düzen içinde bilip takdir etmesi; kaza takdir edilenin gerçekleşmesidir.','İnsan irade ve sorumluluk sahibidir.','Tevekkül çaba gösterdikten sonra sonucu Allah’a bırakmaktır.','Sınava çalışıp sonucu Allah’a bırakmak tevekküldür.','Tevekkülü çalışmadan beklemek olarak yorumlama.'],
    'Zekât ve Sadaka İbadeti':['Zekât belirli şartlara bağlı mali ibadet; sadaka daha geniş kapsamlı gönüllü iyiliktir.','Zekâtın toplumsal dayanışma yönünü bil.','Sadakanın yalnız para olmadığını hatırla.','Güzel söz ve yardım da sadaka kapsamında değerlendirilebilir.','Zekât ve sadakayı aynı şartlara bağlı sanma.'],
    'Friendship Vocabulary':['Friendship ünitesi davet etme, kabul/ret ve mazeret bildirme kalıplarına odaklanır.','Would you like to…? davet kalıbıdır.','I’d love to olumlu cevaptır.','Would you like to come? — I’d love to.','Kibar ret verirken gerekçe eklemeyi unutma.'],
    'Describing Simple Processes':['Bir süreci anlatırken first, then, next, after that, finally gibi sıralama ifadeleri kullanılır.','Emir cümleleri tariflerde yaygındır.','İşlem sırasını bağlaçlarla netleştir.','First chop the onions. Then add them to the pan.','Finally ile ilk adımı başlatma.']
  };
  const subjectFrames={
    mat:{summary:'Bu matematik konusu, verilenleri ilişkilendirip doğru işlem veya modeli kurmayı gerektirir.',keys:['Tanım ve temel kuralı öğren.','Önce kolay örnek, sonra yeni nesil problem çöz.','Sonucu tahmin ederek işlemini kontrol et.'],trap:'Formülü ezberleyip sorudaki koşulu okumadan uygulama.',example:'Verilenleri küçük bir şema veya işlem sırasına dönüştürüp çözümü adım adım kontrol et.'},
    tur:{summary:'Bu Türkçe konusu, metni dikkatle okuyup anlam ilişkisini ve dil bilgisini doğru yorumlamayı gerektirir.',keys:['Sorunun kökünü önce oku.','Metindeki kanıta göre karar ver.','Benzer görünen seçeneklerde küçük anlam farklarını ara.'],trap:'Kendi düşünceni metnin düşüncesi yerine koyma.',example:'Cevabı seçmeden önce metinde seçeneği destekleyen sözcük veya cümleyi bul.'},
    fen:{summary:'Bu Fen Bilimleri konusu, bilimsel kavramları neden-sonuç ilişkisiyle günlük yaşam örneklerine uygulamayı gerektirir.',keys:['Değişkenleri ayırt et.','Grafik/deney düzeneklerinde yalnız değişen koşula odaklan.','Kavramı günlük yaşam örneğiyle eşleştir.'],trap:'Ezber bilgiyi deney koşullarını okumadan kullanma.',example:'Bir deney sorusunda bağımsız, bağımlı ve kontrol edilen değişkenleri işaretle.'},
    ink:{summary:'Bu İnkılap Tarihi konusu, olayların kronolojisini, neden-sonuçlarını ve millî egemenlik/bağımsızlık bağlantılarını yorumlamayı gerektirir.',keys:['Olayın tarihini ve bağlamını birlikte düşün.','Neden-sonuç bağlantısını kur.','Belge ve sözlerden çıkarım yap.'],trap:'Sadece tarih ezberleyip olayın sonucunu gözden kaçırma.',example:'Bir gelişmeyi “neden oldu, ne değiştirdi?” sorularıyla iki cümlede özetle.'},
    din:{summary:'Bu Din Kültürü konusu, temel kavramları ayet/hadis ve günlük yaşam örnekleriyle doğru ilişkilendirmeyi gerektirir.',keys:['Kavramın tanımını kendi cümlenle söyle.','Günlük yaşam örneği üret.','Benzer kavramların farkını belirle.'],trap:'Kavramları yalnız ezber tanımla sınırlama.',example:'Kavramı bir günlük hayat davranışıyla eşleştir ve nedenini açıkla.'},
    eng:{summary:'Bu İngilizce konusu, günlük iletişim kalıplarını bağlama uygun biçimde anlamayı ve kullanmayı gerektirir.',keys:['Anahtar kelimeleri öğren.','Soru-cevap kalıplarını eşleştir.','Kısa diyaloglarla tekrar et.'],trap:'Tek kelime çevirisine bakıp cümlenin bağlamını kaçırma.',example:'Kalıbı bir olumlu ve bir olumsuz cevapla kısa diyalog içinde kullan.'}
  };
  function subjectOf(topic){for(const s of window.LGS_DATA.subjects)for(const u of s.units)if(u.topics.includes(topic))return s;return window.LGS_DATA.subjects[0]}
  function officialFor(topic){const OC=window.LGS_OFFICIAL_CURRICULUM;if(!OC)return[];let hit=null;for(const s of window.LGS_DATA.subjects)for(const u of s.units)if(u.topics.includes(topic))hit={s,u};if(!hit)return[];const os=OC.subjects?.find(x=>x.id===hit.s.id);if(!os)return[];if(hit.s.id==='tur'){const codes=OC.topicOutcomeCodes?.tur?.[topic]||[];return os.groups.flatMap(g=>g.outcomes).filter(o=>codes.includes(o.code));}const g=os.groups.find(g=>g.name===topic)||os.groups.find(g=>g.name===hit.u.name);return g?.outcomes||[];}
  function make(topic){
    const s=subjectOf(topic), frame=subjectFrames[s.id]||subjectFrames.mat, x=specific[topic];
    if(x)return{summary:x[0],keys:[x[1],x[2]],example:x[3],trap:x[4],subject:s.name};
    const unit=s.units.find(u=>u.topics.includes(topic)), oo=officialFor(topic);
    const officialLead=oo.length?`MEB kazanım odağı: ${oo.slice(0,2).map(o=>o.text).join(' ')}`:'';
    const officialKeys=oo.slice(0,3).map(o=>`${o.code}: ${o.text}`);
    return{summary:`${topic}, ${s.name} dersinde “${unit?.name||''}” başlığı altında yer alan bir LGS çalışma konusudur. ${officialLead||frame.summary}`,keys:officialKeys.length?officialKeys:frame.keys,example:`${topic}: ${frame.example}`,trap:frame.trap,subject:s.name};
  }
  window.LGS_LESSON={make,subjectOf};
})();
